apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iam-ismaeel/ApplicationSet-Merge-Gen-GitOps-Manifests.git
    targetRevision: main
    path: api-gateway/base   # Path to the microservice manifests
    kustomize:
      namePrefix: api-
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
