apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iam-ismaeel/DevOps-Engineer-Assessment-CaseStudy-4.git
    targetRevision: main
    path: auth-service/base   # Path to the microservice manifests
    kustomize:
      namePrefix: auth-
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

